# Jekyll Configuration
title: RDF link notes
url: https://notes.rdf.link
description: Knowledge base / personal notebook of Matthieu Bosquet
lang: en
locale: en_GB
theme_color: "#f35f47"
github_username: matthieubosquet
repository: matthieubosquet/notes
source: src
destination: dist
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
homepage:
  title: Notes
  url: /
nav:
  - title: GitHub
    url: https://github.com/matthieubosquet
pagefind: true
check_internal_links: true
check_external_links: true
check_insecure_links: true
styles:
  input: /_styles/
  output: /assets/css/styles.css
  rouge_theme: github
  minify: true
excerpt_separator: <!--more-->
include:
  - _pages
exclude:
  - docker-compose.yml
  - README.md
markdown: kramdown
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
plugins:
  - jekyll-feed
  - jekyll-sitemap
